// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDThmAwlK-rwsPGXZUNCMDxSwU87AyZCk8',
    appId: '1:94918268872:web:5a9482d203540bac2892fd',
    messagingSenderId: '94918268872',
    projectId: 'pertemuan10rea',
    authDomain: 'pertemuan10rea.firebaseapp.com',
    storageBucket: 'pertemuan10rea.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHADBSYQxh7DgfFhQqs8kbKSJFlp4Qh_M',
    appId: '1:94918268872:android:0d78739b8107cd582892fd',
    messagingSenderId: '94918268872',
    projectId: 'pertemuan10rea',
    storageBucket: 'pertemuan10rea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADb3q-pYPpdJ4CO788TAdXuWYR29jDZbM',
    appId: '1:94918268872:ios:03a6bda1410178342892fd',
    messagingSenderId: '94918268872',
    projectId: 'pertemuan10rea',
    storageBucket: 'pertemuan10rea.firebasestorage.app',
    iosBundleId: 'com.example.projectPertemuan10Rea',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADb3q-pYPpdJ4CO788TAdXuWYR29jDZbM',
    appId: '1:94918268872:ios:03a6bda1410178342892fd',
    messagingSenderId: '94918268872',
    projectId: 'pertemuan10rea',
    storageBucket: 'pertemuan10rea.firebasestorage.app',
    iosBundleId: 'com.example.projectPertemuan10Rea',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDThmAwlK-rwsPGXZUNCMDxSwU87AyZCk8',
    appId: '1:94918268872:web:be254d9d8d16c8992892fd',
    messagingSenderId: '94918268872',
    projectId: 'pertemuan10rea',
    authDomain: 'pertemuan10rea.firebaseapp.com',
    storageBucket: 'pertemuan10rea.firebasestorage.app',
  );
}
